version: "3.9"
networks:
 test:
services:
  postgres:
    networks:
      - test
    image: postgres:15-alpine3.17
    environment:
      POSTGRES_DB: "db_date"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
  backend:
    build: .
    image: order_controll_app-web
    command: python main.py
    networks:
      - test
    ports:
      - "5000:5000"
    restart: unless-stopped
    depends_on:
      - postgres
  frontend:
   build:
     dockerfile: order_controll_app/frontend/Dockerfile
   image: react_front
   networks:
      - test
   command: npm start
   ports:
      - "3000:3000"
